
### GET ALL RECIPES
GET  http://localhost:3003/api/recipes HTTP/1.1



### MAKE A RECIPE BY USER1
POST http://localhost:3003/api/recipes HTTP/1.1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNWYxNTFiNjQyODQ5ODIwOTVlZmFjMTI2IiwiaWF0IjoxNTk1MjE5MDg0fQ.evMP3RTrl4ILac7mPQgUr1-lXFm2FrT9FyqJhXQVop8

{
    "title": "title1",
	"ingredients": ["tomato", "coriander", "syrup"],
	"procedure": ["step1", "step2", "step3"],
	"preparationTime": 34,
	"cookTime": 54,
	"totalTime": 88,
	"author": "author1"
}



### MAKE ANOTHER RECIPE BY USER1
POST http://localhost:3003/api/recipes HTTP/1.1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNWYxNTFiNjQyODQ5ODIwOTVlZmFjMTI2IiwiaWF0IjoxNTk1MjE5MDg0fQ.evMP3RTrl4ILac7mPQgUr1-lXFm2FrT9FyqJhXQVop8

{
    "title": "title2",
	"ingredients": ["oil", "red chilis", "ketchup", "batter"],
	"procedure": ["step1", "step2", "step3"],
	"preparationTime": 4,
	"cookTime": 14,
	"totalTime": 18,
	"author": "author1",
	"tags": [{"title": "chocolate", "votes": 1}, {"title": "tomato", "votes": 1}]
}



### MAKE A RECIPE BY USER2
POST http://localhost:3003/api/recipes HTTP/1.1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlkIjoiNWYxNTFiNjgyODQ5ODIwOTVlZmFjMTI3IiwiaWF0IjoxNTk1MjE5MTY3fQ.4noRNFUQuu33hR5yXthnhGhXWRYBcdnCV2J32pD72fI

{
	"title": "title2",
	"ingredients": ["sugar", "salt", "maple", "apple", "banana"],
	"procedure": ["step1", "step2", "step3"],
	"preparationTime": 20,
	"cookTime": 15,
	"totalTime": 35,
	"author": "author1",
	"tags": [{"title": "sweet", "votes": 1}, {"title": "salty", "votes": 1}]
}



### MAKE A RECIPE WITHOUT USER TOKEN
POST http://localhost:3003/api/recipes HTTP/1.1  
Content-Type: application/json

{
	"title": "title2",
	"ingredients": ["sugar", "salt", "maple", "apple", "banana"],
	"procedure": ["step1", "step2", "step3"],
	"preparationTime": 10,
	"cookTime": 5,
	"totalTime": 15,
	"author": "author1",
	"tags": [{"title": "sweet", "votes": 1}, {"title": "salty", "votes": 1}]
}



### DELETE A RECIPE WITH INCORRECT TOKEN
DELETE http://localhost:3003/api/recipes/5f0d503ae5189a84fae1aaf8 HTTP/1.1  



### DELETE A SECOND USER1 RECIPE WITH CORRECT TOKEN
DELETE http://localhost:3003/api/recipes/5f11e3125b87b94b61293d57 HTTP/1.1  
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNWYxMjFjYjY2OTMyOTg1N2MxYzMwZTc5IiwiaWF0IjoxNTk1MDIyNTYxfQ.__LSefUk-meC1W-43D74KmqIGu-1UgXwGdolWFq0shk


### ADD A REVIEW AND TAGS AND RATING TO USER1's FIRST BLOG WITHOUT TOKEN
PUT http://localhost:3003/api/recipes/5f11e3095b87b94b61293d56 HTTP/1.1  
Content-Type: application/json

{
    "reviews": ["This is an amazing recipe (very sweet)", "First RECIPE FOR THE WIN"],
	"tags": [{"title": "chocolate", "votes": 4}, {"title": "sugar", "votes": 8}, {"title": "sugar", "votes": 20}],
	"rating": 3.75
}



### ADD A REVIEW AND TAGS AND RATING TO USER1's FIRST BLOG WITH SOME CORRECT TOKEN
PUT http://localhost:3003/api/recipes/5f151cbe56345f09adcec1d0 HTTP/1.1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNWYxNTFiNjQyODQ5ODIwOTVlZmFjMTI2IiwiaWF0IjoxNTk1MjE5MDg0fQ.evMP3RTrl4ILac7mPQgUr1-lXFm2FrT9FyqJhXQVop8

{
    "reviews": ["This is an amazing recipe (very sweet)", "First RECIPE FOR THE WIN"],
	"tags": [{"title": "chocolate", "votes": 4}, {"title": "sugar", "votes": 8}, {"title": "sugar", "votes": 20}],
	"rating": 3.75,
	"ratingCount": 15
}


