
### GET ALL RECIPES
GET  http://localhost:3003/api/recipes HTTP/1.1



### MAKE A RECIPE BY USER1
POST http://localhost:3003/api/recipes HTTP/1.1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNWYwY2I1ZDUzZTUyN2Q5YWQzZDJkZWNmIiwiaWF0IjoxNTk1MDA3NzM3fQ.lcN3JlW8YvBkoIkkOOaqZAGNy80mo7VuKHpluwX9aLM

{
    "title": "title1",
	"ingredients": ["tomato", "coriander", "syrup"],
	"procedure": "procedure1",
	"preparationTime": 34,
	"cookTime": 54,
	"totalTime": 88,
	"author": "author1"
}



### MAKE ANOTHER RECIPE BY USER1
POST http://localhost:3003/api/recipes HTTP/1.1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNWYwY2I1ZDUzZTUyN2Q5YWQzZDJkZWNmIiwiaWF0IjoxNTk0NzA2ODA0fQ.tPRMhcYqy0-IZofEtkGgj6nQrnyZWKfrDo10Cnvv0jk

{
    "title": "title2",
	"ingredients": ["oil", "red chilis", "ketchup", "batter"],
	"procedure": "procedure1",
	"preparationTime": 4,
	"cookTime": 14,
	"totalTime": 18,
	"author": "author1",
	"tags": [{"title": "chocolate", "votes": 1}, {"title": "tomato", "votes": 1}]
}



### MAKE A RECIPE BY USER2
POST http://localhost:3003/api/recipes HTTP/1.1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMiIsImlkIjoiNWYwY2I1ZDYzZTUyN2Q5YWQzZDJkZWQwIiwiaWF0IjoxNTk1MDA3ODUyfQ.XEXgPXLUkd4m7A2l92e_K5pwaA6JsP9eIey-84YR2GA

{
	"title": "title2",
	"ingredients": ["sugar", "salt", "maple", "apple", "banana"],
	"procedure": "procedure1",
	"preparationTime": 20,
	"cookTime": 15,
	"totalTime": 35,
	"author": "author1",
	"tags": [{"title": "sweet", "votes": 1}, {"title": "salty", "votes": 1}]
}



### MAKE A RECIPE WITHOUT USER TOKEN
POST http://localhost:3003/api/recipes HTTP/1.1  
Content-Type: application/json

{
	"title": "title2",
	"ingredients": ["sugar", "salt", "maple", "apple", "banana"],
	"procedure": "procedure1",
	"preparationTime": 10,
	"cookTime": 5,
	"totalTime": 15,
	"author": "author1",
	"tags": [{"title": "sweet", "votes": 1}, {"title": "salty", "votes": 1}]
}



### DELETE A RECIPE WITH INCORRECT TOKEN
DELETE http://localhost:3003/api/recipes/5f0d503ae5189a84fae1aaf8 HTTP/1.1  



### DELETE A SECOND USER1 RECIPE WITH CORRECT TOKEN
DELETE http://localhost:3003/api/recipes/5f11e3125b87b94b61293d57 HTTP/1.1  
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNWYwY2I1ZDUzZTUyN2Q5YWQzZDJkZWNmIiwiaWF0IjoxNTk1MDA3NzM3fQ.lcN3JlW8YvBkoIkkOOaqZAGNy80mo7VuKHpluwX9aLM


### ADD A REVIEW AND TAGS AND RATING TO USER1's FIRST BLOG WITHOUT TOKEN
PUT http://localhost:3003/api/recipes/5f11e3095b87b94b61293d56 HTTP/1.1  
Content-Type: application/json

{
    "reviews": ["This is an amazing recipe (very sweet)", "First RECIPE FOR THE WIN"],
	"tags": [{"title": "chocolate", "votes": 4}, {"title": "sugar", "votes": 8}, {"title": "sugar", "votes": 20}],
	"rating": 3.75
}



### ADD A REVIEW AND TAGS AND RATING TO USER1's FIRST BLOG WITH SOME CORRECT TOKEN
PUT http://localhost:3003/api/recipes/5f11e3095b87b94b61293d56 HTTP/1.1  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lMSIsImlkIjoiNWYwY2I1ZDUzZTUyN2Q5YWQzZDJkZWNmIiwiaWF0IjoxNTk1MDA3NzM3fQ.lcN3JlW8YvBkoIkkOOaqZAGNy80mo7VuKHpluwX9aLM

{
    "reviews": ["This is an amazing recipe (very sweet)", "First RECIPE FOR THE WIN"],
	"tags": [{"title": "chocolate", "votes": 4}, {"title": "sugar", "votes": 8}, {"title": "sugar", "votes": 20}],
	"rating": 3.75,
	"ratingCount": 15
}


