### GET ALL USERS

GET  http://localhost:3003/api/users HTTP/1.1


### CREATE FIRST USER (send twice to check unique validation)

POST http://localhost:3003/api/users HTTP/1.1  
Content-Type: application/json

{
	"username": "username1",
	"firstName": "firstname1",
	"lastName": "lastname1",
	"password": "password1",
	"email": "user1@gmail.com",
	"tags": [],
	"averageRating": null,
	"favoritedRecipes": [],
	"queuedRecipes": []
}

### CREATE SECOND USER (different from first)
POST http://localhost:3003/api/users HTTP/1.1  
Content-Type: application/json

{
	"username": "username2",
	"firstName": "firstname2",
	"lastName": "lastname2",
	"password": "password2",
	"email": "user2@gmail.com",
	"tags": ["fun"],
	"averageRating": 2,
	"favoritedRecipes": [],
	"queuedRecipes": []
}

### MODIFY SECOND USER INFO (not password) - REPLACE ID WITH USER TWO ID
PUT http://localhost:3003/api/users/5f0ca4843e527d9ad3d2dec1 HTTP/1.1  
Content-Type: application/json

{
	"username": "username2changed",
	"firstName": "firstname2changed",
	"lastName": "lastname2changed",
	"password": "password2",
	"email": "user2changed@gmail.com",
	"tags": ["fun", "changed"],
	"averageRating": 5,
	"favoritedRecipes": ["changed"],
	"queuedRecipes": ["changed"]
}

### MODIFY SECOND USER PASSWORD - REPLACE ID WITH USER TWO ID
PUT http://localhost:3003/api/users/5f0ca4843e527d9ad3d2dec1 HTTP/1.1  
Content-Type: application/json

{
	"username": "username2",
	"firstName": "firstname2",
	"lastName": "lastname2",
	"password": "password2changed",
	"email": "user2@gmail.com",
	"tags": ["fun"],
	"averageRating": 2,
	"favoritedRecipes": [],
	"queuedRecipes": []
}


